version: '3.9'

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/api/src

  worker:
    build: 
      context: ./backend
      dockerfile: Dockerfile.api
    command: python -m celery -A worker.app worker -B
    ports:
      - "5005:5005"
    volumes:
      - ./backend/src:/api/src
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
     - '6379:6379'

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gila
    ports:
      - "5432:5432"